#!/usr/bin/env python3


#LORASERVER configuration
LORASERVER_IP = "127.0.0.1"
LORASERVER_URL = 'http://localhost'
LORASERVER_MQTT_PORT = 1883
LORASERVER_API_PORT = 8080
LORASERVER_USER = 'admin'
LORASERVER_PASS = 'admin'

LORASERVER_SERVICE_PROFILE = 'multicast_sp'
LORASERVER_DOWNLINK_DR = 5
LORASERVER_DOWNLINK_FREQ = 869525000

#update configuration
UPDATE_DELAY = 300

